[package]
name = "scanit"
version = "0.3.4"
rust-version = "1.74.1"
edition = "2021"
description = "A fast, multi-threaded filesystem search tool"
license = "MIT"
documentation = "https://docs.rs/scanit"
repository = "https://github.com/alexcu2718/scanit"
keywords = ["search", "filesystem", "parallel", "regex", "cli"]
categories = ["filesystem", "command-line-utilities", "concurrency"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
ignore = "0.4.23"
regex = "1.11.1"
[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = "0.5.4"


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
debug = true
strip= "symbols"

